language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cadellteng/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cadellteng/docker-react npm run test -- --coverage